/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package autoscalinggroup

import (
	"github.com/aws/aws-sdk-go/aws/awserr"
	svcsdk "github.com/aws/aws-sdk-go/service/autoscaling"

	svcapitypes "github.com/crossplane-contrib/provider-aws/apis/autoscaling/v1alpha1"
)

// NOTE(muvaf): We return pointers in case the function needs to start with an
// empty object, hence need to return a new pointer.

// GenerateDescribeAutoScalingGroupsInput returns input for read
// operation.
func GenerateDescribeAutoScalingGroupsInput(cr *svcapitypes.AutoScalingGroup) *svcsdk.DescribeAutoScalingGroupsInput {
	res := &svcsdk.DescribeAutoScalingGroupsInput{}

	if cr.Spec.ForProvider.AutoScalingGroupName != nil {
		f0 := []*string{}
		f0 = append(f0, cr.Spec.ForProvider.AutoScalingGroupName)
		res.SetAutoScalingGroupNames(f0)
	}

	return res
}

// GenerateAutoScalingGroup returns the current state in the form of *svcapitypes.AutoScalingGroup.
func GenerateAutoScalingGroup(resp *svcsdk.DescribeAutoScalingGroupsOutput) *svcapitypes.AutoScalingGroup {
	cr := &svcapitypes.AutoScalingGroup{}

	found := false
	for _, elem := range resp.AutoScalingGroups {
		if elem.AutoScalingGroupName != nil {
			cr.Spec.ForProvider.AutoScalingGroupName = elem.AutoScalingGroupName
		} else {
			cr.Spec.ForProvider.AutoScalingGroupName = nil
		}
		if elem.AvailabilityZones != nil {
			f2 := []*string{}
			for _, f2iter := range elem.AvailabilityZones {
				var f2elem string
				f2elem = *f2iter
				f2 = append(f2, &f2elem)
			}
			cr.Spec.ForProvider.AvailabilityZones = f2
		} else {
			cr.Spec.ForProvider.AvailabilityZones = nil
		}
		if elem.CapacityRebalance != nil {
			cr.Spec.ForProvider.CapacityRebalance = elem.CapacityRebalance
		} else {
			cr.Spec.ForProvider.CapacityRebalance = nil
		}
		if elem.Context != nil {
			cr.Spec.ForProvider.Context = elem.Context
		} else {
			cr.Spec.ForProvider.Context = nil
		}
		if elem.DefaultCooldown != nil {
			cr.Spec.ForProvider.DefaultCooldown = elem.DefaultCooldown
		} else {
			cr.Spec.ForProvider.DefaultCooldown = nil
		}
		if elem.DefaultInstanceWarmup != nil {
			cr.Spec.ForProvider.DefaultInstanceWarmup = elem.DefaultInstanceWarmup
		} else {
			cr.Spec.ForProvider.DefaultInstanceWarmup = nil
		}
		if elem.DesiredCapacity != nil {
			cr.Spec.ForProvider.DesiredCapacity = elem.DesiredCapacity
		} else {
			cr.Spec.ForProvider.DesiredCapacity = nil
		}
		if elem.DesiredCapacityType != nil {
			cr.Spec.ForProvider.DesiredCapacityType = elem.DesiredCapacityType
		} else {
			cr.Spec.ForProvider.DesiredCapacityType = nil
		}
		if elem.HealthCheckGracePeriod != nil {
			cr.Spec.ForProvider.HealthCheckGracePeriod = elem.HealthCheckGracePeriod
		} else {
			cr.Spec.ForProvider.HealthCheckGracePeriod = nil
		}
		if elem.HealthCheckType != nil {
			cr.Spec.ForProvider.HealthCheckType = elem.HealthCheckType
		} else {
			cr.Spec.ForProvider.HealthCheckType = nil
		}
		if elem.LaunchConfigurationName != nil {
			cr.Spec.ForProvider.LaunchConfigurationName = elem.LaunchConfigurationName
		} else {
			cr.Spec.ForProvider.LaunchConfigurationName = nil
		}
		if elem.LaunchTemplate != nil {
			f15 := &svcapitypes.LaunchTemplateSpecification{}
			if elem.LaunchTemplate.LaunchTemplateId != nil {
				f15.LaunchTemplateID = elem.LaunchTemplate.LaunchTemplateId
			}
			if elem.LaunchTemplate.LaunchTemplateName != nil {
				f15.LaunchTemplateName = elem.LaunchTemplate.LaunchTemplateName
			}
			if elem.LaunchTemplate.Version != nil {
				f15.Version = elem.LaunchTemplate.Version
			}
			cr.Spec.ForProvider.LaunchTemplate = f15
		} else {
			cr.Spec.ForProvider.LaunchTemplate = nil
		}
		if elem.LoadBalancerNames != nil {
			f16 := []*string{}
			for _, f16iter := range elem.LoadBalancerNames {
				var f16elem string
				f16elem = *f16iter
				f16 = append(f16, &f16elem)
			}
			cr.Spec.ForProvider.LoadBalancerNames = f16
		} else {
			cr.Spec.ForProvider.LoadBalancerNames = nil
		}
		if elem.MaxInstanceLifetime != nil {
			cr.Spec.ForProvider.MaxInstanceLifetime = elem.MaxInstanceLifetime
		} else {
			cr.Spec.ForProvider.MaxInstanceLifetime = nil
		}
		if elem.MaxSize != nil {
			cr.Spec.ForProvider.MaxSize = elem.MaxSize
		} else {
			cr.Spec.ForProvider.MaxSize = nil
		}
		if elem.MinSize != nil {
			cr.Spec.ForProvider.MinSize = elem.MinSize
		} else {
			cr.Spec.ForProvider.MinSize = nil
		}
		if elem.MixedInstancesPolicy != nil {
			f20 := &svcapitypes.MixedInstancesPolicy{}
			if elem.MixedInstancesPolicy.InstancesDistribution != nil {
				f20f0 := &svcapitypes.InstancesDistribution{}
				if elem.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy != nil {
					f20f0.OnDemandAllocationStrategy = elem.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy
				}
				if elem.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity != nil {
					f20f0.OnDemandBaseCapacity = elem.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity
				}
				if elem.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity != nil {
					f20f0.OnDemandPercentageAboveBaseCapacity = elem.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity
				}
				if elem.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy != nil {
					f20f0.SpotAllocationStrategy = elem.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy
				}
				if elem.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools != nil {
					f20f0.SpotInstancePools = elem.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools
				}
				if elem.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice != nil {
					f20f0.SpotMaxPrice = elem.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice
				}
				f20.InstancesDistribution = f20f0
			}
			if elem.MixedInstancesPolicy.LaunchTemplate != nil {
				f20f1 := &svcapitypes.LaunchTemplate{}
				if elem.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification != nil {
					f20f1f0 := &svcapitypes.LaunchTemplateSpecification{}
					if elem.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateId != nil {
						f20f1f0.LaunchTemplateID = elem.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateId
					}
					if elem.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName != nil {
						f20f1f0.LaunchTemplateName = elem.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName
					}
					if elem.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version != nil {
						f20f1f0.Version = elem.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version
					}
					f20f1.LaunchTemplateSpecification = f20f1f0
				}
				if elem.MixedInstancesPolicy.LaunchTemplate.Overrides != nil {
					f20f1f1 := []*svcapitypes.LaunchTemplateOverrides{}
					for _, f20f1f1iter := range elem.MixedInstancesPolicy.LaunchTemplate.Overrides {
						f20f1f1elem := &svcapitypes.LaunchTemplateOverrides{}
						if f20f1f1iter.InstanceRequirements != nil {
							f20f1f1elemf0 := &svcapitypes.InstanceRequirements{}
							if f20f1f1iter.InstanceRequirements.AcceleratorCount != nil {
								f20f1f1elemf0f0 := &svcapitypes.AcceleratorCountRequest{}
								if f20f1f1iter.InstanceRequirements.AcceleratorCount.Max != nil {
									f20f1f1elemf0f0.Max = f20f1f1iter.InstanceRequirements.AcceleratorCount.Max
								}
								if f20f1f1iter.InstanceRequirements.AcceleratorCount.Min != nil {
									f20f1f1elemf0f0.Min = f20f1f1iter.InstanceRequirements.AcceleratorCount.Min
								}
								f20f1f1elemf0.AcceleratorCount = f20f1f1elemf0f0
							}
							if f20f1f1iter.InstanceRequirements.AcceleratorManufacturers != nil {
								f20f1f1elemf0f1 := []*string{}
								for _, f20f1f1elemf0f1iter := range f20f1f1iter.InstanceRequirements.AcceleratorManufacturers {
									var f20f1f1elemf0f1elem string
									f20f1f1elemf0f1elem = *f20f1f1elemf0f1iter
									f20f1f1elemf0f1 = append(f20f1f1elemf0f1, &f20f1f1elemf0f1elem)
								}
								f20f1f1elemf0.AcceleratorManufacturers = f20f1f1elemf0f1
							}
							if f20f1f1iter.InstanceRequirements.AcceleratorNames != nil {
								f20f1f1elemf0f2 := []*string{}
								for _, f20f1f1elemf0f2iter := range f20f1f1iter.InstanceRequirements.AcceleratorNames {
									var f20f1f1elemf0f2elem string
									f20f1f1elemf0f2elem = *f20f1f1elemf0f2iter
									f20f1f1elemf0f2 = append(f20f1f1elemf0f2, &f20f1f1elemf0f2elem)
								}
								f20f1f1elemf0.AcceleratorNames = f20f1f1elemf0f2
							}
							if f20f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB != nil {
								f20f1f1elemf0f3 := &svcapitypes.AcceleratorTotalMemoryMiBRequest{}
								if f20f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Max != nil {
									f20f1f1elemf0f3.Max = f20f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Max
								}
								if f20f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Min != nil {
									f20f1f1elemf0f3.Min = f20f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Min
								}
								f20f1f1elemf0.AcceleratorTotalMemoryMiB = f20f1f1elemf0f3
							}
							if f20f1f1iter.InstanceRequirements.AcceleratorTypes != nil {
								f20f1f1elemf0f4 := []*string{}
								for _, f20f1f1elemf0f4iter := range f20f1f1iter.InstanceRequirements.AcceleratorTypes {
									var f20f1f1elemf0f4elem string
									f20f1f1elemf0f4elem = *f20f1f1elemf0f4iter
									f20f1f1elemf0f4 = append(f20f1f1elemf0f4, &f20f1f1elemf0f4elem)
								}
								f20f1f1elemf0.AcceleratorTypes = f20f1f1elemf0f4
							}
							if f20f1f1iter.InstanceRequirements.BareMetal != nil {
								f20f1f1elemf0.BareMetal = f20f1f1iter.InstanceRequirements.BareMetal
							}
							if f20f1f1iter.InstanceRequirements.BaselineEbsBandwidthMbps != nil {
								f20f1f1elemf0f6 := &svcapitypes.BaselineEBSBandwidthMbpsRequest{}
								if f20f1f1iter.InstanceRequirements.BaselineEbsBandwidthMbps.Max != nil {
									f20f1f1elemf0f6.Max = f20f1f1iter.InstanceRequirements.BaselineEbsBandwidthMbps.Max
								}
								if f20f1f1iter.InstanceRequirements.BaselineEbsBandwidthMbps.Min != nil {
									f20f1f1elemf0f6.Min = f20f1f1iter.InstanceRequirements.BaselineEbsBandwidthMbps.Min
								}
								f20f1f1elemf0.BaselineEBSBandwidthMbps = f20f1f1elemf0f6
							}
							if f20f1f1iter.InstanceRequirements.BurstablePerformance != nil {
								f20f1f1elemf0.BurstablePerformance = f20f1f1iter.InstanceRequirements.BurstablePerformance
							}
							if f20f1f1iter.InstanceRequirements.CpuManufacturers != nil {
								f20f1f1elemf0f8 := []*string{}
								for _, f20f1f1elemf0f8iter := range f20f1f1iter.InstanceRequirements.CpuManufacturers {
									var f20f1f1elemf0f8elem string
									f20f1f1elemf0f8elem = *f20f1f1elemf0f8iter
									f20f1f1elemf0f8 = append(f20f1f1elemf0f8, &f20f1f1elemf0f8elem)
								}
								f20f1f1elemf0.CPUManufacturers = f20f1f1elemf0f8
							}
							if f20f1f1iter.InstanceRequirements.ExcludedInstanceTypes != nil {
								f20f1f1elemf0f9 := []*string{}
								for _, f20f1f1elemf0f9iter := range f20f1f1iter.InstanceRequirements.ExcludedInstanceTypes {
									var f20f1f1elemf0f9elem string
									f20f1f1elemf0f9elem = *f20f1f1elemf0f9iter
									f20f1f1elemf0f9 = append(f20f1f1elemf0f9, &f20f1f1elemf0f9elem)
								}
								f20f1f1elemf0.ExcludedInstanceTypes = f20f1f1elemf0f9
							}
							if f20f1f1iter.InstanceRequirements.InstanceGenerations != nil {
								f20f1f1elemf0f10 := []*string{}
								for _, f20f1f1elemf0f10iter := range f20f1f1iter.InstanceRequirements.InstanceGenerations {
									var f20f1f1elemf0f10elem string
									f20f1f1elemf0f10elem = *f20f1f1elemf0f10iter
									f20f1f1elemf0f10 = append(f20f1f1elemf0f10, &f20f1f1elemf0f10elem)
								}
								f20f1f1elemf0.InstanceGenerations = f20f1f1elemf0f10
							}
							if f20f1f1iter.InstanceRequirements.LocalStorage != nil {
								f20f1f1elemf0.LocalStorage = f20f1f1iter.InstanceRequirements.LocalStorage
							}
							if f20f1f1iter.InstanceRequirements.LocalStorageTypes != nil {
								f20f1f1elemf0f12 := []*string{}
								for _, f20f1f1elemf0f12iter := range f20f1f1iter.InstanceRequirements.LocalStorageTypes {
									var f20f1f1elemf0f12elem string
									f20f1f1elemf0f12elem = *f20f1f1elemf0f12iter
									f20f1f1elemf0f12 = append(f20f1f1elemf0f12, &f20f1f1elemf0f12elem)
								}
								f20f1f1elemf0.LocalStorageTypes = f20f1f1elemf0f12
							}
							if f20f1f1iter.InstanceRequirements.MemoryGiBPerVCpu != nil {
								f20f1f1elemf0f13 := &svcapitypes.MemoryGiBPerVCPURequest{}
								if f20f1f1iter.InstanceRequirements.MemoryGiBPerVCpu.Max != nil {
									f20f1f1elemf0f13.Max = f20f1f1iter.InstanceRequirements.MemoryGiBPerVCpu.Max
								}
								if f20f1f1iter.InstanceRequirements.MemoryGiBPerVCpu.Min != nil {
									f20f1f1elemf0f13.Min = f20f1f1iter.InstanceRequirements.MemoryGiBPerVCpu.Min
								}
								f20f1f1elemf0.MemoryGiBPerVCPU = f20f1f1elemf0f13
							}
							if f20f1f1iter.InstanceRequirements.MemoryMiB != nil {
								f20f1f1elemf0f14 := &svcapitypes.MemoryMiBRequest{}
								if f20f1f1iter.InstanceRequirements.MemoryMiB.Max != nil {
									f20f1f1elemf0f14.Max = f20f1f1iter.InstanceRequirements.MemoryMiB.Max
								}
								if f20f1f1iter.InstanceRequirements.MemoryMiB.Min != nil {
									f20f1f1elemf0f14.Min = f20f1f1iter.InstanceRequirements.MemoryMiB.Min
								}
								f20f1f1elemf0.MemoryMiB = f20f1f1elemf0f14
							}
							if f20f1f1iter.InstanceRequirements.NetworkInterfaceCount != nil {
								f20f1f1elemf0f15 := &svcapitypes.NetworkInterfaceCountRequest{}
								if f20f1f1iter.InstanceRequirements.NetworkInterfaceCount.Max != nil {
									f20f1f1elemf0f15.Max = f20f1f1iter.InstanceRequirements.NetworkInterfaceCount.Max
								}
								if f20f1f1iter.InstanceRequirements.NetworkInterfaceCount.Min != nil {
									f20f1f1elemf0f15.Min = f20f1f1iter.InstanceRequirements.NetworkInterfaceCount.Min
								}
								f20f1f1elemf0.NetworkInterfaceCount = f20f1f1elemf0f15
							}
							if f20f1f1iter.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice != nil {
								f20f1f1elemf0.OnDemandMaxPricePercentageOverLowestPrice = f20f1f1iter.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice
							}
							if f20f1f1iter.InstanceRequirements.RequireHibernateSupport != nil {
								f20f1f1elemf0.RequireHibernateSupport = f20f1f1iter.InstanceRequirements.RequireHibernateSupport
							}
							if f20f1f1iter.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice != nil {
								f20f1f1elemf0.SpotMaxPricePercentageOverLowestPrice = f20f1f1iter.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice
							}
							if f20f1f1iter.InstanceRequirements.TotalLocalStorageGB != nil {
								f20f1f1elemf0f19 := &svcapitypes.TotalLocalStorageGBRequest{}
								if f20f1f1iter.InstanceRequirements.TotalLocalStorageGB.Max != nil {
									f20f1f1elemf0f19.Max = f20f1f1iter.InstanceRequirements.TotalLocalStorageGB.Max
								}
								if f20f1f1iter.InstanceRequirements.TotalLocalStorageGB.Min != nil {
									f20f1f1elemf0f19.Min = f20f1f1iter.InstanceRequirements.TotalLocalStorageGB.Min
								}
								f20f1f1elemf0.TotalLocalStorageGB = f20f1f1elemf0f19
							}
							if f20f1f1iter.InstanceRequirements.VCpuCount != nil {
								f20f1f1elemf0f20 := &svcapitypes.VCPUCountRequest{}
								if f20f1f1iter.InstanceRequirements.VCpuCount.Max != nil {
									f20f1f1elemf0f20.Max = f20f1f1iter.InstanceRequirements.VCpuCount.Max
								}
								if f20f1f1iter.InstanceRequirements.VCpuCount.Min != nil {
									f20f1f1elemf0f20.Min = f20f1f1iter.InstanceRequirements.VCpuCount.Min
								}
								f20f1f1elemf0.VCPUCount = f20f1f1elemf0f20
							}
							f20f1f1elem.InstanceRequirements = f20f1f1elemf0
						}
						if f20f1f1iter.InstanceType != nil {
							f20f1f1elem.InstanceType = f20f1f1iter.InstanceType
						}
						if f20f1f1iter.LaunchTemplateSpecification != nil {
							f20f1f1elemf2 := &svcapitypes.LaunchTemplateSpecification{}
							if f20f1f1iter.LaunchTemplateSpecification.LaunchTemplateId != nil {
								f20f1f1elemf2.LaunchTemplateID = f20f1f1iter.LaunchTemplateSpecification.LaunchTemplateId
							}
							if f20f1f1iter.LaunchTemplateSpecification.LaunchTemplateName != nil {
								f20f1f1elemf2.LaunchTemplateName = f20f1f1iter.LaunchTemplateSpecification.LaunchTemplateName
							}
							if f20f1f1iter.LaunchTemplateSpecification.Version != nil {
								f20f1f1elemf2.Version = f20f1f1iter.LaunchTemplateSpecification.Version
							}
							f20f1f1elem.LaunchTemplateSpecification = f20f1f1elemf2
						}
						if f20f1f1iter.WeightedCapacity != nil {
							f20f1f1elem.WeightedCapacity = f20f1f1iter.WeightedCapacity
						}
						f20f1f1 = append(f20f1f1, f20f1f1elem)
					}
					f20f1.Overrides = f20f1f1
				}
				f20.LaunchTemplate = f20f1
			}
			cr.Spec.ForProvider.MixedInstancesPolicy = f20
		} else {
			cr.Spec.ForProvider.MixedInstancesPolicy = nil
		}
		if elem.NewInstancesProtectedFromScaleIn != nil {
			cr.Spec.ForProvider.NewInstancesProtectedFromScaleIn = elem.NewInstancesProtectedFromScaleIn
		} else {
			cr.Spec.ForProvider.NewInstancesProtectedFromScaleIn = nil
		}
		if elem.PlacementGroup != nil {
			cr.Spec.ForProvider.PlacementGroup = elem.PlacementGroup
		} else {
			cr.Spec.ForProvider.PlacementGroup = nil
		}
		if elem.ServiceLinkedRoleARN != nil {
			cr.Spec.ForProvider.ServiceLinkedRoleARN = elem.ServiceLinkedRoleARN
		} else {
			cr.Spec.ForProvider.ServiceLinkedRoleARN = nil
		}
		if elem.Tags != nil {
			f27 := []*svcapitypes.Tag{}
			for _, f27iter := range elem.Tags {
				f27elem := &svcapitypes.Tag{}
				if f27iter.Key != nil {
					f27elem.Key = f27iter.Key
				}
				if f27iter.PropagateAtLaunch != nil {
					f27elem.PropagateAtLaunch = f27iter.PropagateAtLaunch
				}
				if f27iter.ResourceId != nil {
					f27elem.ResourceID = f27iter.ResourceId
				}
				if f27iter.ResourceType != nil {
					f27elem.ResourceType = f27iter.ResourceType
				}
				if f27iter.Value != nil {
					f27elem.Value = f27iter.Value
				}
				f27 = append(f27, f27elem)
			}
			cr.Spec.ForProvider.Tags = f27
		} else {
			cr.Spec.ForProvider.Tags = nil
		}
		if elem.TargetGroupARNs != nil {
			f28 := []*string{}
			for _, f28iter := range elem.TargetGroupARNs {
				var f28elem string
				f28elem = *f28iter
				f28 = append(f28, &f28elem)
			}
			cr.Spec.ForProvider.TargetGroupARNs = f28
		} else {
			cr.Spec.ForProvider.TargetGroupARNs = nil
		}
		if elem.TerminationPolicies != nil {
			f29 := []*string{}
			for _, f29iter := range elem.TerminationPolicies {
				var f29elem string
				f29elem = *f29iter
				f29 = append(f29, &f29elem)
			}
			cr.Spec.ForProvider.TerminationPolicies = f29
		} else {
			cr.Spec.ForProvider.TerminationPolicies = nil
		}
		if elem.VPCZoneIdentifier != nil {
			cr.Spec.ForProvider.VPCZoneIdentifier = elem.VPCZoneIdentifier
		} else {
			cr.Spec.ForProvider.VPCZoneIdentifier = nil
		}
		found = true
		break
	}
	if !found {
		return cr
	}

	return cr
}

// GenerateCreateAutoScalingGroupInput returns a create input.
func GenerateCreateAutoScalingGroupInput(cr *svcapitypes.AutoScalingGroup) *svcsdk.CreateAutoScalingGroupInput {
	res := &svcsdk.CreateAutoScalingGroupInput{}

	if cr.Spec.ForProvider.AutoScalingGroupName != nil {
		res.SetAutoScalingGroupName(*cr.Spec.ForProvider.AutoScalingGroupName)
	}
	if cr.Spec.ForProvider.AvailabilityZones != nil {
		f1 := []*string{}
		for _, f1iter := range cr.Spec.ForProvider.AvailabilityZones {
			var f1elem string
			f1elem = *f1iter
			f1 = append(f1, &f1elem)
		}
		res.SetAvailabilityZones(f1)
	}
	if cr.Spec.ForProvider.CapacityRebalance != nil {
		res.SetCapacityRebalance(*cr.Spec.ForProvider.CapacityRebalance)
	}
	if cr.Spec.ForProvider.Context != nil {
		res.SetContext(*cr.Spec.ForProvider.Context)
	}
	if cr.Spec.ForProvider.DefaultCooldown != nil {
		res.SetDefaultCooldown(*cr.Spec.ForProvider.DefaultCooldown)
	}
	if cr.Spec.ForProvider.DefaultInstanceWarmup != nil {
		res.SetDefaultInstanceWarmup(*cr.Spec.ForProvider.DefaultInstanceWarmup)
	}
	if cr.Spec.ForProvider.DesiredCapacity != nil {
		res.SetDesiredCapacity(*cr.Spec.ForProvider.DesiredCapacity)
	}
	if cr.Spec.ForProvider.DesiredCapacityType != nil {
		res.SetDesiredCapacityType(*cr.Spec.ForProvider.DesiredCapacityType)
	}
	if cr.Spec.ForProvider.HealthCheckGracePeriod != nil {
		res.SetHealthCheckGracePeriod(*cr.Spec.ForProvider.HealthCheckGracePeriod)
	}
	if cr.Spec.ForProvider.HealthCheckType != nil {
		res.SetHealthCheckType(*cr.Spec.ForProvider.HealthCheckType)
	}
	if cr.Spec.ForProvider.InstanceID != nil {
		res.SetInstanceId(*cr.Spec.ForProvider.InstanceID)
	}
	if cr.Spec.ForProvider.LaunchConfigurationName != nil {
		res.SetLaunchConfigurationName(*cr.Spec.ForProvider.LaunchConfigurationName)
	}
	if cr.Spec.ForProvider.LaunchTemplate != nil {
		f12 := &svcsdk.LaunchTemplateSpecification{}
		if cr.Spec.ForProvider.LaunchTemplate.LaunchTemplateID != nil {
			f12.SetLaunchTemplateId(*cr.Spec.ForProvider.LaunchTemplate.LaunchTemplateID)
		}
		if cr.Spec.ForProvider.LaunchTemplate.LaunchTemplateName != nil {
			f12.SetLaunchTemplateName(*cr.Spec.ForProvider.LaunchTemplate.LaunchTemplateName)
		}
		if cr.Spec.ForProvider.LaunchTemplate.Version != nil {
			f12.SetVersion(*cr.Spec.ForProvider.LaunchTemplate.Version)
		}
		res.SetLaunchTemplate(f12)
	}
	if cr.Spec.ForProvider.LifecycleHookSpecificationList != nil {
		f13 := []*svcsdk.LifecycleHookSpecification{}
		for _, f13iter := range cr.Spec.ForProvider.LifecycleHookSpecificationList {
			f13elem := &svcsdk.LifecycleHookSpecification{}
			if f13iter.DefaultResult != nil {
				f13elem.SetDefaultResult(*f13iter.DefaultResult)
			}
			if f13iter.HeartbeatTimeout != nil {
				f13elem.SetHeartbeatTimeout(*f13iter.HeartbeatTimeout)
			}
			if f13iter.LifecycleHookName != nil {
				f13elem.SetLifecycleHookName(*f13iter.LifecycleHookName)
			}
			if f13iter.LifecycleTransition != nil {
				f13elem.SetLifecycleTransition(*f13iter.LifecycleTransition)
			}
			if f13iter.NotificationMetadata != nil {
				f13elem.SetNotificationMetadata(*f13iter.NotificationMetadata)
			}
			if f13iter.NotificationTargetARN != nil {
				f13elem.SetNotificationTargetARN(*f13iter.NotificationTargetARN)
			}
			if f13iter.RoleARN != nil {
				f13elem.SetRoleARN(*f13iter.RoleARN)
			}
			f13 = append(f13, f13elem)
		}
		res.SetLifecycleHookSpecificationList(f13)
	}
	if cr.Spec.ForProvider.LoadBalancerNames != nil {
		f14 := []*string{}
		for _, f14iter := range cr.Spec.ForProvider.LoadBalancerNames {
			var f14elem string
			f14elem = *f14iter
			f14 = append(f14, &f14elem)
		}
		res.SetLoadBalancerNames(f14)
	}
	if cr.Spec.ForProvider.MaxInstanceLifetime != nil {
		res.SetMaxInstanceLifetime(*cr.Spec.ForProvider.MaxInstanceLifetime)
	}
	if cr.Spec.ForProvider.MaxSize != nil {
		res.SetMaxSize(*cr.Spec.ForProvider.MaxSize)
	}
	if cr.Spec.ForProvider.MinSize != nil {
		res.SetMinSize(*cr.Spec.ForProvider.MinSize)
	}
	if cr.Spec.ForProvider.MixedInstancesPolicy != nil {
		f18 := &svcsdk.MixedInstancesPolicy{}
		if cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution != nil {
			f18f0 := &svcsdk.InstancesDistribution{}
			if cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy != nil {
				f18f0.SetOnDemandAllocationStrategy(*cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy)
			}
			if cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity != nil {
				f18f0.SetOnDemandBaseCapacity(*cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity)
			}
			if cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity != nil {
				f18f0.SetOnDemandPercentageAboveBaseCapacity(*cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity)
			}
			if cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy != nil {
				f18f0.SetSpotAllocationStrategy(*cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy)
			}
			if cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools != nil {
				f18f0.SetSpotInstancePools(*cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools)
			}
			if cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice != nil {
				f18f0.SetSpotMaxPrice(*cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice)
			}
			f18.SetInstancesDistribution(f18f0)
		}
		if cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate != nil {
			f18f1 := &svcsdk.LaunchTemplate{}
			if cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification != nil {
				f18f1f0 := &svcsdk.LaunchTemplateSpecification{}
				if cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateID != nil {
					f18f1f0.SetLaunchTemplateId(*cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateID)
				}
				if cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName != nil {
					f18f1f0.SetLaunchTemplateName(*cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName)
				}
				if cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version != nil {
					f18f1f0.SetVersion(*cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version)
				}
				f18f1.SetLaunchTemplateSpecification(f18f1f0)
			}
			if cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate.Overrides != nil {
				f18f1f1 := []*svcsdk.LaunchTemplateOverrides{}
				for _, f18f1f1iter := range cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate.Overrides {
					f18f1f1elem := &svcsdk.LaunchTemplateOverrides{}
					if f18f1f1iter.InstanceRequirements != nil {
						f18f1f1elemf0 := &svcsdk.InstanceRequirements{}
						if f18f1f1iter.InstanceRequirements.AcceleratorCount != nil {
							f18f1f1elemf0f0 := &svcsdk.AcceleratorCountRequest{}
							if f18f1f1iter.InstanceRequirements.AcceleratorCount.Max != nil {
								f18f1f1elemf0f0.SetMax(*f18f1f1iter.InstanceRequirements.AcceleratorCount.Max)
							}
							if f18f1f1iter.InstanceRequirements.AcceleratorCount.Min != nil {
								f18f1f1elemf0f0.SetMin(*f18f1f1iter.InstanceRequirements.AcceleratorCount.Min)
							}
							f18f1f1elemf0.SetAcceleratorCount(f18f1f1elemf0f0)
						}
						if f18f1f1iter.InstanceRequirements.AcceleratorManufacturers != nil {
							f18f1f1elemf0f1 := []*string{}
							for _, f18f1f1elemf0f1iter := range f18f1f1iter.InstanceRequirements.AcceleratorManufacturers {
								var f18f1f1elemf0f1elem string
								f18f1f1elemf0f1elem = *f18f1f1elemf0f1iter
								f18f1f1elemf0f1 = append(f18f1f1elemf0f1, &f18f1f1elemf0f1elem)
							}
							f18f1f1elemf0.SetAcceleratorManufacturers(f18f1f1elemf0f1)
						}
						if f18f1f1iter.InstanceRequirements.AcceleratorNames != nil {
							f18f1f1elemf0f2 := []*string{}
							for _, f18f1f1elemf0f2iter := range f18f1f1iter.InstanceRequirements.AcceleratorNames {
								var f18f1f1elemf0f2elem string
								f18f1f1elemf0f2elem = *f18f1f1elemf0f2iter
								f18f1f1elemf0f2 = append(f18f1f1elemf0f2, &f18f1f1elemf0f2elem)
							}
							f18f1f1elemf0.SetAcceleratorNames(f18f1f1elemf0f2)
						}
						if f18f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB != nil {
							f18f1f1elemf0f3 := &svcsdk.AcceleratorTotalMemoryMiBRequest{}
							if f18f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Max != nil {
								f18f1f1elemf0f3.SetMax(*f18f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Max)
							}
							if f18f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Min != nil {
								f18f1f1elemf0f3.SetMin(*f18f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Min)
							}
							f18f1f1elemf0.SetAcceleratorTotalMemoryMiB(f18f1f1elemf0f3)
						}
						if f18f1f1iter.InstanceRequirements.AcceleratorTypes != nil {
							f18f1f1elemf0f4 := []*string{}
							for _, f18f1f1elemf0f4iter := range f18f1f1iter.InstanceRequirements.AcceleratorTypes {
								var f18f1f1elemf0f4elem string
								f18f1f1elemf0f4elem = *f18f1f1elemf0f4iter
								f18f1f1elemf0f4 = append(f18f1f1elemf0f4, &f18f1f1elemf0f4elem)
							}
							f18f1f1elemf0.SetAcceleratorTypes(f18f1f1elemf0f4)
						}
						if f18f1f1iter.InstanceRequirements.BareMetal != nil {
							f18f1f1elemf0.SetBareMetal(*f18f1f1iter.InstanceRequirements.BareMetal)
						}
						if f18f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps != nil {
							f18f1f1elemf0f6 := &svcsdk.BaselineEbsBandwidthMbpsRequest{}
							if f18f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps.Max != nil {
								f18f1f1elemf0f6.SetMax(*f18f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps.Max)
							}
							if f18f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps.Min != nil {
								f18f1f1elemf0f6.SetMin(*f18f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps.Min)
							}
							f18f1f1elemf0.SetBaselineEbsBandwidthMbps(f18f1f1elemf0f6)
						}
						if f18f1f1iter.InstanceRequirements.BurstablePerformance != nil {
							f18f1f1elemf0.SetBurstablePerformance(*f18f1f1iter.InstanceRequirements.BurstablePerformance)
						}
						if f18f1f1iter.InstanceRequirements.CPUManufacturers != nil {
							f18f1f1elemf0f8 := []*string{}
							for _, f18f1f1elemf0f8iter := range f18f1f1iter.InstanceRequirements.CPUManufacturers {
								var f18f1f1elemf0f8elem string
								f18f1f1elemf0f8elem = *f18f1f1elemf0f8iter
								f18f1f1elemf0f8 = append(f18f1f1elemf0f8, &f18f1f1elemf0f8elem)
							}
							f18f1f1elemf0.SetCpuManufacturers(f18f1f1elemf0f8)
						}
						if f18f1f1iter.InstanceRequirements.ExcludedInstanceTypes != nil {
							f18f1f1elemf0f9 := []*string{}
							for _, f18f1f1elemf0f9iter := range f18f1f1iter.InstanceRequirements.ExcludedInstanceTypes {
								var f18f1f1elemf0f9elem string
								f18f1f1elemf0f9elem = *f18f1f1elemf0f9iter
								f18f1f1elemf0f9 = append(f18f1f1elemf0f9, &f18f1f1elemf0f9elem)
							}
							f18f1f1elemf0.SetExcludedInstanceTypes(f18f1f1elemf0f9)
						}
						if f18f1f1iter.InstanceRequirements.InstanceGenerations != nil {
							f18f1f1elemf0f10 := []*string{}
							for _, f18f1f1elemf0f10iter := range f18f1f1iter.InstanceRequirements.InstanceGenerations {
								var f18f1f1elemf0f10elem string
								f18f1f1elemf0f10elem = *f18f1f1elemf0f10iter
								f18f1f1elemf0f10 = append(f18f1f1elemf0f10, &f18f1f1elemf0f10elem)
							}
							f18f1f1elemf0.SetInstanceGenerations(f18f1f1elemf0f10)
						}
						if f18f1f1iter.InstanceRequirements.LocalStorage != nil {
							f18f1f1elemf0.SetLocalStorage(*f18f1f1iter.InstanceRequirements.LocalStorage)
						}
						if f18f1f1iter.InstanceRequirements.LocalStorageTypes != nil {
							f18f1f1elemf0f12 := []*string{}
							for _, f18f1f1elemf0f12iter := range f18f1f1iter.InstanceRequirements.LocalStorageTypes {
								var f18f1f1elemf0f12elem string
								f18f1f1elemf0f12elem = *f18f1f1elemf0f12iter
								f18f1f1elemf0f12 = append(f18f1f1elemf0f12, &f18f1f1elemf0f12elem)
							}
							f18f1f1elemf0.SetLocalStorageTypes(f18f1f1elemf0f12)
						}
						if f18f1f1iter.InstanceRequirements.MemoryGiBPerVCPU != nil {
							f18f1f1elemf0f13 := &svcsdk.MemoryGiBPerVCpuRequest{}
							if f18f1f1iter.InstanceRequirements.MemoryGiBPerVCPU.Max != nil {
								f18f1f1elemf0f13.SetMax(*f18f1f1iter.InstanceRequirements.MemoryGiBPerVCPU.Max)
							}
							if f18f1f1iter.InstanceRequirements.MemoryGiBPerVCPU.Min != nil {
								f18f1f1elemf0f13.SetMin(*f18f1f1iter.InstanceRequirements.MemoryGiBPerVCPU.Min)
							}
							f18f1f1elemf0.SetMemoryGiBPerVCpu(f18f1f1elemf0f13)
						}
						if f18f1f1iter.InstanceRequirements.MemoryMiB != nil {
							f18f1f1elemf0f14 := &svcsdk.MemoryMiBRequest{}
							if f18f1f1iter.InstanceRequirements.MemoryMiB.Max != nil {
								f18f1f1elemf0f14.SetMax(*f18f1f1iter.InstanceRequirements.MemoryMiB.Max)
							}
							if f18f1f1iter.InstanceRequirements.MemoryMiB.Min != nil {
								f18f1f1elemf0f14.SetMin(*f18f1f1iter.InstanceRequirements.MemoryMiB.Min)
							}
							f18f1f1elemf0.SetMemoryMiB(f18f1f1elemf0f14)
						}
						if f18f1f1iter.InstanceRequirements.NetworkInterfaceCount != nil {
							f18f1f1elemf0f15 := &svcsdk.NetworkInterfaceCountRequest{}
							if f18f1f1iter.InstanceRequirements.NetworkInterfaceCount.Max != nil {
								f18f1f1elemf0f15.SetMax(*f18f1f1iter.InstanceRequirements.NetworkInterfaceCount.Max)
							}
							if f18f1f1iter.InstanceRequirements.NetworkInterfaceCount.Min != nil {
								f18f1f1elemf0f15.SetMin(*f18f1f1iter.InstanceRequirements.NetworkInterfaceCount.Min)
							}
							f18f1f1elemf0.SetNetworkInterfaceCount(f18f1f1elemf0f15)
						}
						if f18f1f1iter.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice != nil {
							f18f1f1elemf0.SetOnDemandMaxPricePercentageOverLowestPrice(*f18f1f1iter.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice)
						}
						if f18f1f1iter.InstanceRequirements.RequireHibernateSupport != nil {
							f18f1f1elemf0.SetRequireHibernateSupport(*f18f1f1iter.InstanceRequirements.RequireHibernateSupport)
						}
						if f18f1f1iter.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice != nil {
							f18f1f1elemf0.SetSpotMaxPricePercentageOverLowestPrice(*f18f1f1iter.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice)
						}
						if f18f1f1iter.InstanceRequirements.TotalLocalStorageGB != nil {
							f18f1f1elemf0f19 := &svcsdk.TotalLocalStorageGBRequest{}
							if f18f1f1iter.InstanceRequirements.TotalLocalStorageGB.Max != nil {
								f18f1f1elemf0f19.SetMax(*f18f1f1iter.InstanceRequirements.TotalLocalStorageGB.Max)
							}
							if f18f1f1iter.InstanceRequirements.TotalLocalStorageGB.Min != nil {
								f18f1f1elemf0f19.SetMin(*f18f1f1iter.InstanceRequirements.TotalLocalStorageGB.Min)
							}
							f18f1f1elemf0.SetTotalLocalStorageGB(f18f1f1elemf0f19)
						}
						if f18f1f1iter.InstanceRequirements.VCPUCount != nil {
							f18f1f1elemf0f20 := &svcsdk.VCpuCountRequest{}
							if f18f1f1iter.InstanceRequirements.VCPUCount.Max != nil {
								f18f1f1elemf0f20.SetMax(*f18f1f1iter.InstanceRequirements.VCPUCount.Max)
							}
							if f18f1f1iter.InstanceRequirements.VCPUCount.Min != nil {
								f18f1f1elemf0f20.SetMin(*f18f1f1iter.InstanceRequirements.VCPUCount.Min)
							}
							f18f1f1elemf0.SetVCpuCount(f18f1f1elemf0f20)
						}
						f18f1f1elem.SetInstanceRequirements(f18f1f1elemf0)
					}
					if f18f1f1iter.InstanceType != nil {
						f18f1f1elem.SetInstanceType(*f18f1f1iter.InstanceType)
					}
					if f18f1f1iter.LaunchTemplateSpecification != nil {
						f18f1f1elemf2 := &svcsdk.LaunchTemplateSpecification{}
						if f18f1f1iter.LaunchTemplateSpecification.LaunchTemplateID != nil {
							f18f1f1elemf2.SetLaunchTemplateId(*f18f1f1iter.LaunchTemplateSpecification.LaunchTemplateID)
						}
						if f18f1f1iter.LaunchTemplateSpecification.LaunchTemplateName != nil {
							f18f1f1elemf2.SetLaunchTemplateName(*f18f1f1iter.LaunchTemplateSpecification.LaunchTemplateName)
						}
						if f18f1f1iter.LaunchTemplateSpecification.Version != nil {
							f18f1f1elemf2.SetVersion(*f18f1f1iter.LaunchTemplateSpecification.Version)
						}
						f18f1f1elem.SetLaunchTemplateSpecification(f18f1f1elemf2)
					}
					if f18f1f1iter.WeightedCapacity != nil {
						f18f1f1elem.SetWeightedCapacity(*f18f1f1iter.WeightedCapacity)
					}
					f18f1f1 = append(f18f1f1, f18f1f1elem)
				}
				f18f1.SetOverrides(f18f1f1)
			}
			f18.SetLaunchTemplate(f18f1)
		}
		res.SetMixedInstancesPolicy(f18)
	}
	if cr.Spec.ForProvider.NewInstancesProtectedFromScaleIn != nil {
		res.SetNewInstancesProtectedFromScaleIn(*cr.Spec.ForProvider.NewInstancesProtectedFromScaleIn)
	}
	if cr.Spec.ForProvider.PlacementGroup != nil {
		res.SetPlacementGroup(*cr.Spec.ForProvider.PlacementGroup)
	}
	if cr.Spec.ForProvider.ServiceLinkedRoleARN != nil {
		res.SetServiceLinkedRoleARN(*cr.Spec.ForProvider.ServiceLinkedRoleARN)
	}
	if cr.Spec.ForProvider.Tags != nil {
		f22 := []*svcsdk.Tag{}
		for _, f22iter := range cr.Spec.ForProvider.Tags {
			f22elem := &svcsdk.Tag{}
			if f22iter.Key != nil {
				f22elem.SetKey(*f22iter.Key)
			}
			if f22iter.PropagateAtLaunch != nil {
				f22elem.SetPropagateAtLaunch(*f22iter.PropagateAtLaunch)
			}
			if f22iter.ResourceID != nil {
				f22elem.SetResourceId(*f22iter.ResourceID)
			}
			if f22iter.ResourceType != nil {
				f22elem.SetResourceType(*f22iter.ResourceType)
			}
			if f22iter.Value != nil {
				f22elem.SetValue(*f22iter.Value)
			}
			f22 = append(f22, f22elem)
		}
		res.SetTags(f22)
	}
	if cr.Spec.ForProvider.TargetGroupARNs != nil {
		f23 := []*string{}
		for _, f23iter := range cr.Spec.ForProvider.TargetGroupARNs {
			var f23elem string
			f23elem = *f23iter
			f23 = append(f23, &f23elem)
		}
		res.SetTargetGroupARNs(f23)
	}
	if cr.Spec.ForProvider.TerminationPolicies != nil {
		f24 := []*string{}
		for _, f24iter := range cr.Spec.ForProvider.TerminationPolicies {
			var f24elem string
			f24elem = *f24iter
			f24 = append(f24, &f24elem)
		}
		res.SetTerminationPolicies(f24)
	}
	if cr.Spec.ForProvider.VPCZoneIdentifier != nil {
		res.SetVPCZoneIdentifier(*cr.Spec.ForProvider.VPCZoneIdentifier)
	}

	return res
}

// GenerateUpdateAutoScalingGroupInput returns an update input.
func GenerateUpdateAutoScalingGroupInput(cr *svcapitypes.AutoScalingGroup) *svcsdk.UpdateAutoScalingGroupInput {
	res := &svcsdk.UpdateAutoScalingGroupInput{}

	if cr.Spec.ForProvider.AutoScalingGroupName != nil {
		res.SetAutoScalingGroupName(*cr.Spec.ForProvider.AutoScalingGroupName)
	}
	if cr.Spec.ForProvider.AvailabilityZones != nil {
		f1 := []*string{}
		for _, f1iter := range cr.Spec.ForProvider.AvailabilityZones {
			var f1elem string
			f1elem = *f1iter
			f1 = append(f1, &f1elem)
		}
		res.SetAvailabilityZones(f1)
	}
	if cr.Spec.ForProvider.CapacityRebalance != nil {
		res.SetCapacityRebalance(*cr.Spec.ForProvider.CapacityRebalance)
	}
	if cr.Spec.ForProvider.Context != nil {
		res.SetContext(*cr.Spec.ForProvider.Context)
	}
	if cr.Spec.ForProvider.DefaultCooldown != nil {
		res.SetDefaultCooldown(*cr.Spec.ForProvider.DefaultCooldown)
	}
	if cr.Spec.ForProvider.DefaultInstanceWarmup != nil {
		res.SetDefaultInstanceWarmup(*cr.Spec.ForProvider.DefaultInstanceWarmup)
	}
	if cr.Spec.ForProvider.DesiredCapacity != nil {
		res.SetDesiredCapacity(*cr.Spec.ForProvider.DesiredCapacity)
	}
	if cr.Spec.ForProvider.DesiredCapacityType != nil {
		res.SetDesiredCapacityType(*cr.Spec.ForProvider.DesiredCapacityType)
	}
	if cr.Spec.ForProvider.HealthCheckGracePeriod != nil {
		res.SetHealthCheckGracePeriod(*cr.Spec.ForProvider.HealthCheckGracePeriod)
	}
	if cr.Spec.ForProvider.HealthCheckType != nil {
		res.SetHealthCheckType(*cr.Spec.ForProvider.HealthCheckType)
	}
	if cr.Spec.ForProvider.LaunchConfigurationName != nil {
		res.SetLaunchConfigurationName(*cr.Spec.ForProvider.LaunchConfigurationName)
	}
	if cr.Spec.ForProvider.LaunchTemplate != nil {
		f11 := &svcsdk.LaunchTemplateSpecification{}
		if cr.Spec.ForProvider.LaunchTemplate.LaunchTemplateID != nil {
			f11.SetLaunchTemplateId(*cr.Spec.ForProvider.LaunchTemplate.LaunchTemplateID)
		}
		if cr.Spec.ForProvider.LaunchTemplate.LaunchTemplateName != nil {
			f11.SetLaunchTemplateName(*cr.Spec.ForProvider.LaunchTemplate.LaunchTemplateName)
		}
		if cr.Spec.ForProvider.LaunchTemplate.Version != nil {
			f11.SetVersion(*cr.Spec.ForProvider.LaunchTemplate.Version)
		}
		res.SetLaunchTemplate(f11)
	}
	if cr.Spec.ForProvider.MaxInstanceLifetime != nil {
		res.SetMaxInstanceLifetime(*cr.Spec.ForProvider.MaxInstanceLifetime)
	}
	if cr.Spec.ForProvider.MaxSize != nil {
		res.SetMaxSize(*cr.Spec.ForProvider.MaxSize)
	}
	if cr.Spec.ForProvider.MinSize != nil {
		res.SetMinSize(*cr.Spec.ForProvider.MinSize)
	}
	if cr.Spec.ForProvider.MixedInstancesPolicy != nil {
		f15 := &svcsdk.MixedInstancesPolicy{}
		if cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution != nil {
			f15f0 := &svcsdk.InstancesDistribution{}
			if cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy != nil {
				f15f0.SetOnDemandAllocationStrategy(*cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy)
			}
			if cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity != nil {
				f15f0.SetOnDemandBaseCapacity(*cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity)
			}
			if cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity != nil {
				f15f0.SetOnDemandPercentageAboveBaseCapacity(*cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity)
			}
			if cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy != nil {
				f15f0.SetSpotAllocationStrategy(*cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy)
			}
			if cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools != nil {
				f15f0.SetSpotInstancePools(*cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools)
			}
			if cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice != nil {
				f15f0.SetSpotMaxPrice(*cr.Spec.ForProvider.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice)
			}
			f15.SetInstancesDistribution(f15f0)
		}
		if cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate != nil {
			f15f1 := &svcsdk.LaunchTemplate{}
			if cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification != nil {
				f15f1f0 := &svcsdk.LaunchTemplateSpecification{}
				if cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateID != nil {
					f15f1f0.SetLaunchTemplateId(*cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateID)
				}
				if cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName != nil {
					f15f1f0.SetLaunchTemplateName(*cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName)
				}
				if cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version != nil {
					f15f1f0.SetVersion(*cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version)
				}
				f15f1.SetLaunchTemplateSpecification(f15f1f0)
			}
			if cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate.Overrides != nil {
				f15f1f1 := []*svcsdk.LaunchTemplateOverrides{}
				for _, f15f1f1iter := range cr.Spec.ForProvider.MixedInstancesPolicy.LaunchTemplate.Overrides {
					f15f1f1elem := &svcsdk.LaunchTemplateOverrides{}
					if f15f1f1iter.InstanceRequirements != nil {
						f15f1f1elemf0 := &svcsdk.InstanceRequirements{}
						if f15f1f1iter.InstanceRequirements.AcceleratorCount != nil {
							f15f1f1elemf0f0 := &svcsdk.AcceleratorCountRequest{}
							if f15f1f1iter.InstanceRequirements.AcceleratorCount.Max != nil {
								f15f1f1elemf0f0.SetMax(*f15f1f1iter.InstanceRequirements.AcceleratorCount.Max)
							}
							if f15f1f1iter.InstanceRequirements.AcceleratorCount.Min != nil {
								f15f1f1elemf0f0.SetMin(*f15f1f1iter.InstanceRequirements.AcceleratorCount.Min)
							}
							f15f1f1elemf0.SetAcceleratorCount(f15f1f1elemf0f0)
						}
						if f15f1f1iter.InstanceRequirements.AcceleratorManufacturers != nil {
							f15f1f1elemf0f1 := []*string{}
							for _, f15f1f1elemf0f1iter := range f15f1f1iter.InstanceRequirements.AcceleratorManufacturers {
								var f15f1f1elemf0f1elem string
								f15f1f1elemf0f1elem = *f15f1f1elemf0f1iter
								f15f1f1elemf0f1 = append(f15f1f1elemf0f1, &f15f1f1elemf0f1elem)
							}
							f15f1f1elemf0.SetAcceleratorManufacturers(f15f1f1elemf0f1)
						}
						if f15f1f1iter.InstanceRequirements.AcceleratorNames != nil {
							f15f1f1elemf0f2 := []*string{}
							for _, f15f1f1elemf0f2iter := range f15f1f1iter.InstanceRequirements.AcceleratorNames {
								var f15f1f1elemf0f2elem string
								f15f1f1elemf0f2elem = *f15f1f1elemf0f2iter
								f15f1f1elemf0f2 = append(f15f1f1elemf0f2, &f15f1f1elemf0f2elem)
							}
							f15f1f1elemf0.SetAcceleratorNames(f15f1f1elemf0f2)
						}
						if f15f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB != nil {
							f15f1f1elemf0f3 := &svcsdk.AcceleratorTotalMemoryMiBRequest{}
							if f15f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Max != nil {
								f15f1f1elemf0f3.SetMax(*f15f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Max)
							}
							if f15f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Min != nil {
								f15f1f1elemf0f3.SetMin(*f15f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Min)
							}
							f15f1f1elemf0.SetAcceleratorTotalMemoryMiB(f15f1f1elemf0f3)
						}
						if f15f1f1iter.InstanceRequirements.AcceleratorTypes != nil {
							f15f1f1elemf0f4 := []*string{}
							for _, f15f1f1elemf0f4iter := range f15f1f1iter.InstanceRequirements.AcceleratorTypes {
								var f15f1f1elemf0f4elem string
								f15f1f1elemf0f4elem = *f15f1f1elemf0f4iter
								f15f1f1elemf0f4 = append(f15f1f1elemf0f4, &f15f1f1elemf0f4elem)
							}
							f15f1f1elemf0.SetAcceleratorTypes(f15f1f1elemf0f4)
						}
						if f15f1f1iter.InstanceRequirements.BareMetal != nil {
							f15f1f1elemf0.SetBareMetal(*f15f1f1iter.InstanceRequirements.BareMetal)
						}
						if f15f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps != nil {
							f15f1f1elemf0f6 := &svcsdk.BaselineEbsBandwidthMbpsRequest{}
							if f15f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps.Max != nil {
								f15f1f1elemf0f6.SetMax(*f15f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps.Max)
							}
							if f15f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps.Min != nil {
								f15f1f1elemf0f6.SetMin(*f15f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps.Min)
							}
							f15f1f1elemf0.SetBaselineEbsBandwidthMbps(f15f1f1elemf0f6)
						}
						if f15f1f1iter.InstanceRequirements.BurstablePerformance != nil {
							f15f1f1elemf0.SetBurstablePerformance(*f15f1f1iter.InstanceRequirements.BurstablePerformance)
						}
						if f15f1f1iter.InstanceRequirements.CPUManufacturers != nil {
							f15f1f1elemf0f8 := []*string{}
							for _, f15f1f1elemf0f8iter := range f15f1f1iter.InstanceRequirements.CPUManufacturers {
								var f15f1f1elemf0f8elem string
								f15f1f1elemf0f8elem = *f15f1f1elemf0f8iter
								f15f1f1elemf0f8 = append(f15f1f1elemf0f8, &f15f1f1elemf0f8elem)
							}
							f15f1f1elemf0.SetCpuManufacturers(f15f1f1elemf0f8)
						}
						if f15f1f1iter.InstanceRequirements.ExcludedInstanceTypes != nil {
							f15f1f1elemf0f9 := []*string{}
							for _, f15f1f1elemf0f9iter := range f15f1f1iter.InstanceRequirements.ExcludedInstanceTypes {
								var f15f1f1elemf0f9elem string
								f15f1f1elemf0f9elem = *f15f1f1elemf0f9iter
								f15f1f1elemf0f9 = append(f15f1f1elemf0f9, &f15f1f1elemf0f9elem)
							}
							f15f1f1elemf0.SetExcludedInstanceTypes(f15f1f1elemf0f9)
						}
						if f15f1f1iter.InstanceRequirements.InstanceGenerations != nil {
							f15f1f1elemf0f10 := []*string{}
							for _, f15f1f1elemf0f10iter := range f15f1f1iter.InstanceRequirements.InstanceGenerations {
								var f15f1f1elemf0f10elem string
								f15f1f1elemf0f10elem = *f15f1f1elemf0f10iter
								f15f1f1elemf0f10 = append(f15f1f1elemf0f10, &f15f1f1elemf0f10elem)
							}
							f15f1f1elemf0.SetInstanceGenerations(f15f1f1elemf0f10)
						}
						if f15f1f1iter.InstanceRequirements.LocalStorage != nil {
							f15f1f1elemf0.SetLocalStorage(*f15f1f1iter.InstanceRequirements.LocalStorage)
						}
						if f15f1f1iter.InstanceRequirements.LocalStorageTypes != nil {
							f15f1f1elemf0f12 := []*string{}
							for _, f15f1f1elemf0f12iter := range f15f1f1iter.InstanceRequirements.LocalStorageTypes {
								var f15f1f1elemf0f12elem string
								f15f1f1elemf0f12elem = *f15f1f1elemf0f12iter
								f15f1f1elemf0f12 = append(f15f1f1elemf0f12, &f15f1f1elemf0f12elem)
							}
							f15f1f1elemf0.SetLocalStorageTypes(f15f1f1elemf0f12)
						}
						if f15f1f1iter.InstanceRequirements.MemoryGiBPerVCPU != nil {
							f15f1f1elemf0f13 := &svcsdk.MemoryGiBPerVCpuRequest{}
							if f15f1f1iter.InstanceRequirements.MemoryGiBPerVCPU.Max != nil {
								f15f1f1elemf0f13.SetMax(*f15f1f1iter.InstanceRequirements.MemoryGiBPerVCPU.Max)
							}
							if f15f1f1iter.InstanceRequirements.MemoryGiBPerVCPU.Min != nil {
								f15f1f1elemf0f13.SetMin(*f15f1f1iter.InstanceRequirements.MemoryGiBPerVCPU.Min)
							}
							f15f1f1elemf0.SetMemoryGiBPerVCpu(f15f1f1elemf0f13)
						}
						if f15f1f1iter.InstanceRequirements.MemoryMiB != nil {
							f15f1f1elemf0f14 := &svcsdk.MemoryMiBRequest{}
							if f15f1f1iter.InstanceRequirements.MemoryMiB.Max != nil {
								f15f1f1elemf0f14.SetMax(*f15f1f1iter.InstanceRequirements.MemoryMiB.Max)
							}
							if f15f1f1iter.InstanceRequirements.MemoryMiB.Min != nil {
								f15f1f1elemf0f14.SetMin(*f15f1f1iter.InstanceRequirements.MemoryMiB.Min)
							}
							f15f1f1elemf0.SetMemoryMiB(f15f1f1elemf0f14)
						}
						if f15f1f1iter.InstanceRequirements.NetworkInterfaceCount != nil {
							f15f1f1elemf0f15 := &svcsdk.NetworkInterfaceCountRequest{}
							if f15f1f1iter.InstanceRequirements.NetworkInterfaceCount.Max != nil {
								f15f1f1elemf0f15.SetMax(*f15f1f1iter.InstanceRequirements.NetworkInterfaceCount.Max)
							}
							if f15f1f1iter.InstanceRequirements.NetworkInterfaceCount.Min != nil {
								f15f1f1elemf0f15.SetMin(*f15f1f1iter.InstanceRequirements.NetworkInterfaceCount.Min)
							}
							f15f1f1elemf0.SetNetworkInterfaceCount(f15f1f1elemf0f15)
						}
						if f15f1f1iter.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice != nil {
							f15f1f1elemf0.SetOnDemandMaxPricePercentageOverLowestPrice(*f15f1f1iter.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice)
						}
						if f15f1f1iter.InstanceRequirements.RequireHibernateSupport != nil {
							f15f1f1elemf0.SetRequireHibernateSupport(*f15f1f1iter.InstanceRequirements.RequireHibernateSupport)
						}
						if f15f1f1iter.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice != nil {
							f15f1f1elemf0.SetSpotMaxPricePercentageOverLowestPrice(*f15f1f1iter.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice)
						}
						if f15f1f1iter.InstanceRequirements.TotalLocalStorageGB != nil {
							f15f1f1elemf0f19 := &svcsdk.TotalLocalStorageGBRequest{}
							if f15f1f1iter.InstanceRequirements.TotalLocalStorageGB.Max != nil {
								f15f1f1elemf0f19.SetMax(*f15f1f1iter.InstanceRequirements.TotalLocalStorageGB.Max)
							}
							if f15f1f1iter.InstanceRequirements.TotalLocalStorageGB.Min != nil {
								f15f1f1elemf0f19.SetMin(*f15f1f1iter.InstanceRequirements.TotalLocalStorageGB.Min)
							}
							f15f1f1elemf0.SetTotalLocalStorageGB(f15f1f1elemf0f19)
						}
						if f15f1f1iter.InstanceRequirements.VCPUCount != nil {
							f15f1f1elemf0f20 := &svcsdk.VCpuCountRequest{}
							if f15f1f1iter.InstanceRequirements.VCPUCount.Max != nil {
								f15f1f1elemf0f20.SetMax(*f15f1f1iter.InstanceRequirements.VCPUCount.Max)
							}
							if f15f1f1iter.InstanceRequirements.VCPUCount.Min != nil {
								f15f1f1elemf0f20.SetMin(*f15f1f1iter.InstanceRequirements.VCPUCount.Min)
							}
							f15f1f1elemf0.SetVCpuCount(f15f1f1elemf0f20)
						}
						f15f1f1elem.SetInstanceRequirements(f15f1f1elemf0)
					}
					if f15f1f1iter.InstanceType != nil {
						f15f1f1elem.SetInstanceType(*f15f1f1iter.InstanceType)
					}
					if f15f1f1iter.LaunchTemplateSpecification != nil {
						f15f1f1elemf2 := &svcsdk.LaunchTemplateSpecification{}
						if f15f1f1iter.LaunchTemplateSpecification.LaunchTemplateID != nil {
							f15f1f1elemf2.SetLaunchTemplateId(*f15f1f1iter.LaunchTemplateSpecification.LaunchTemplateID)
						}
						if f15f1f1iter.LaunchTemplateSpecification.LaunchTemplateName != nil {
							f15f1f1elemf2.SetLaunchTemplateName(*f15f1f1iter.LaunchTemplateSpecification.LaunchTemplateName)
						}
						if f15f1f1iter.LaunchTemplateSpecification.Version != nil {
							f15f1f1elemf2.SetVersion(*f15f1f1iter.LaunchTemplateSpecification.Version)
						}
						f15f1f1elem.SetLaunchTemplateSpecification(f15f1f1elemf2)
					}
					if f15f1f1iter.WeightedCapacity != nil {
						f15f1f1elem.SetWeightedCapacity(*f15f1f1iter.WeightedCapacity)
					}
					f15f1f1 = append(f15f1f1, f15f1f1elem)
				}
				f15f1.SetOverrides(f15f1f1)
			}
			f15.SetLaunchTemplate(f15f1)
		}
		res.SetMixedInstancesPolicy(f15)
	}
	if cr.Spec.ForProvider.NewInstancesProtectedFromScaleIn != nil {
		res.SetNewInstancesProtectedFromScaleIn(*cr.Spec.ForProvider.NewInstancesProtectedFromScaleIn)
	}
	if cr.Spec.ForProvider.PlacementGroup != nil {
		res.SetPlacementGroup(*cr.Spec.ForProvider.PlacementGroup)
	}
	if cr.Spec.ForProvider.ServiceLinkedRoleARN != nil {
		res.SetServiceLinkedRoleARN(*cr.Spec.ForProvider.ServiceLinkedRoleARN)
	}
	if cr.Spec.ForProvider.TerminationPolicies != nil {
		f19 := []*string{}
		for _, f19iter := range cr.Spec.ForProvider.TerminationPolicies {
			var f19elem string
			f19elem = *f19iter
			f19 = append(f19, &f19elem)
		}
		res.SetTerminationPolicies(f19)
	}
	if cr.Spec.ForProvider.VPCZoneIdentifier != nil {
		res.SetVPCZoneIdentifier(*cr.Spec.ForProvider.VPCZoneIdentifier)
	}

	return res
}

// GenerateDeleteAutoScalingGroupInput returns a deletion input.
func GenerateDeleteAutoScalingGroupInput(cr *svcapitypes.AutoScalingGroup) *svcsdk.DeleteAutoScalingGroupInput {
	res := &svcsdk.DeleteAutoScalingGroupInput{}

	if cr.Spec.ForProvider.AutoScalingGroupName != nil {
		res.SetAutoScalingGroupName(*cr.Spec.ForProvider.AutoScalingGroupName)
	}

	return res
}

// IsNotFound returns whether the given error is of type NotFound or not.
func IsNotFound(err error) bool {
	awsErr, ok := err.(awserr.Error)
	return ok && awsErr.Code() == "UNKNOWN"
}
